apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote
spec:
  template:
    spec:
      containers:
      - name: quote
        env:
          - name: PORT
            value: "8080"
          - name: TARGET
            value: "Production cluster"