apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote
  labels:
    app: quote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote
  template:
    metadata:
      labels:
        app: quote
    spec:
      containers:
      - name: quote
        image: quote
        env:
          - name: PORT
            value: "8080"
          - name: TARGET
            value: "Local Dev"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 10001