apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote
  labels:
    app: quote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote
  template:
    metadata:
      labels:
        app: quote
    spec:
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: quote
        securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            privileged: false
        image: quote
        env:
          - name: PORT
            value: "8080"
          - name: TARGET
            value: "LOCAL Dev"